'use strict';

let errs = {
    IN_OKCODE : 0,
    IN_ERRCODE : -10199,
    IN_XRPCFail : -10101,
    IN_XRPC_NotOpen : -10102,
    IN_Mbus_NotOpen : -10103,
    IN_SendError : -10104,
    IN_XMsgFail : -10105,
    IN_InvalidData : -10106,
    IN_NoRcveFunc : -10107,
    IN_UnknownData : -10108,
    IN_OKMSG : "OK",
    IN_XRPCFail_Msg : "in: xRPC open error",
    IN_XRPC_NotOpen_Msg : "in: xRPC not open",
    IN_Mbus_NotOpen_Msg : "in: Motebus not open",
    IN_SendError_Msg : "in: Send error",
    IN_XMsgFail_Msg : "in: XMsg open error",
    IN_InvalidData_Msg : "in: Invalid data",
    IN_NoRcveFunc_Msg : "in: No exist function",
    IN_UnknownData_Msg : "in: Unkwown data",
    MC_OKCODE : 0,
    MC_ERRCODE : -10299,
    MC_NullDC : -10201,
    MC_NotOpen : -10202,
    MC_InvalidData : -10203,
    MC_InvalidSToken : -10204,
    MC_NoRcveFunc : -10205,
    MC_NoMatchDDN : -10206,
    MC_NullDDN : -10207,
    MC_OKMSG : "OK",
    MC_NullDC_Msg : "mc: DC blank",
    MC_NotOpen_Msg : "mc: Not open",
    MC_InvalidData_Msg : "mc: Invalid data",
    MC_InvalidSToken_Msg : "mc: Invalid SToken",
    MC_NoRcveFunc_Msg : "mc: No exist function",
    MC_NoMatchDDN_Msg : "mc: No DDN or Off",
    MC_NullDDN_Msg : "mc: DDN blank",
    WS_OKCODE : 0,
    WS_ERRCODE : -10399,
    WS_InvalidData : -10301,
    WS_NoMatchDDN : -10302,
    WS_NoFunc : -10303,
    WS_OKMSG : "OK",
    WS_InvalidData_Msg : "ws: Invalid data",
    WS_NoMatchDDN_Msg : "ws: No socket id",
    WS_NoFunc_Msg : "ws: No function"
};

module.exports =
        Object.freeze(errs); // freeze prevents changes by users
