'use strict';

let errs = {
    IN_OKCODE : 0,
    IN_ERRCODE : -10199,
    IN_XRPCFail : -10101,
    IN_XRPC_NotOpen : -10102,
    IN_Mbus_NotOpen : -10103,
    IN_SendError : -10104,
    IN_XMsgFail : -10105,
    IN_InvalidData : -10106,
    IN_NoRcveFunc : -10107,
    IN_UnknownData : -10108,
    IN_DataOverSize : -10109,
    IN_OKMSG : "OK",
    IN_XRPCFail_Msg : "xRPC not ready",
    IN_XRPC_NotOpen_Msg : "xRPC not open",
    IN_Mbus_NotOpen_Msg : "Motebus not ready",
    IN_SendError_Msg : "Send error",
    IN_XMsgFail_Msg : "XMsg open error",
    IN_InvalidData_Msg : "Invalid data",
    IN_NoRcveFunc_Msg : "No exist function",
    IN_UnknownData_Msg : "Unkwown data",
    IN_DataOverSize_Msg : "Data over size",
    MC_OKCODE : 0,
    MC_ERRCODE : -10299,
    MC_NullDC : -10201,
    MC_NotOpen : -10202,
    MC_InvalidData : -10203,
    MC_InvalidSToken : -10204,
    MC_NoRcveFunc : -10205,
    MC_NoMatchDDN : -10206,
    MC_NullDDN : -10207,
    MC_InProcess : -10208,
    MC_NoReg: -10209,
    MC_OKMSG : "OK",
    MC_NullDC_Msg : "DC blank",
    MC_NotOpen_Msg : "Not ready",
    MC_InvalidData_Msg : "Invalid data",
    MC_InvalidSToken_Msg : "Invalid SToken",
    MC_NoRcveFunc_Msg : "No exist function",
    MC_NoMatchDDN_Msg : "DDN Off",
    MC_NullDDN_Msg : "DDN blank",
    MC_InProcess_Msg : "In Process",
    MC_NoReg_Msg: "Not reg",
    WS_OKCODE : 0,
    WS_ERRCODE : -10399,
    WS_InvalidData : -10301,
    WS_NoMatchDDN : -10302,
    WS_NoFunc : -10303,
    WS_InvalidSToken : -10304,
    WS_OKMSG : "OK",
    WS_InvalidData_Msg : "Invalid data",
    WS_NoMatchDDN_Msg : "No socket id",
    WS_NoFunc_Msg : "No function",
    WS_InvalidSToken_Msg : "Invalid SToken",
};

module.exports =
        Object.freeze(errs); // freeze prevents changes by users
